In [ ]:
import pandas as pd
avaliacoes = pd.read_excel('/content/drive/MyDrive/MBA/Web Mining e Social Network Analysis/aula/data/kindle_review/reviews.xlsx')

In [ ]:
import nltk
import re
nltk.download('stopwords')
nltk.download('rslp')
nltk.download('punkt')

stemmer = nltk.stem.RSLPStemmer()

def stemmer_tokenizer(doc):
  # considerar somente termos com letras e pelo menos 3 caracteres
    termos = [termo for termo in nltk.word_tokenize(doc) if re.match(r'^[^\W\d]{3,}$', termo)]    
    # aplicar stemmer
    termos = [stemmer.stem(termo) for termo in termos]
    return termos

# stopwords stemmer
stopwords = [stemmer.stem(s) for s in nltk.corpus.stopwords.words('portuguese')]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Package rslp is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
avaliacoes = avaliacoes[avaliacoes.estrelas == 1]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    binary=False,
    norm='l1',
    use_idf = False,
    stop_words=stopwords,
    tokenizer = stemmer_tokenizer
)

vetor = vectorizer.fit_transform(avaliacoes.texto)
vetor

/usr/local/lib/python3.6/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['es', 'estivés', 'fos', 'fôs', 'houvés', 'is', 'nos', 'tivés'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


<285x1289 sparse matrix of type '<class 'numpy.float64'>'
	with 5437 stored elements in Compressed Sparse Row format>

In [ ]:
print(vetor.toarray())
print(vectorizer.get_feature_names())
print(len(vectorizer.get_feature_names()))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['abaix', 'abc', 'abcd', 'aberr', 'aborrec', 'abort', 'abr', 'absurd', 'abund', 'abus', 'aca', 'acab', 'acadêm', 'aceit', 'acend', 'acerv', 'aces', 'acess', 'ach', 'acim', 'acinzent', 'acion', 'aconselh', 'acontec', 'acord', 'acostum', 'acredit', 'acus', 'adapt', 'adequ', 'adiant', 'adic', 'adicion', 'adivinh', 'admit', 'ador', 'adot', 'adquir', 'advert', 'afinal', 'afirm', 'afob', 'agor', 'agrad', 'agradeç', 'aguard', 'aguardando', 'aguent', 'aind', 'ajud', 'ajust', 'alberion', 'aleat', 'aleg', 'alert', 'alg', 'algu', 'algum', 'alguém', 'aliás', 'alm', 'alt', 'altern', 'alus', 'além', 'amarel', 'amazom', 'amazon', 'ambi', 'amig', 'ampl', 'ampli', 'anci', 'and', 'anex', 'ano', 'ant', 'anteced', 'anteri', 'antig', 'antirreflex', 'anunci', 'anúnci', 'aond', 'apag', 'aparec', 'aparelh', 'aparelhodecepcionadasempr', 'aparent', 'apen', '

In [ ]:
vetor.argmax(1)


matrix([[ 719],
        [  66],
        [1255],
        [ 185],
        [ 185],
        [ 885],
        [ 236],
        [ 316],
        [ 719],
        [ 565],
        [ 367],
        [ 599],
        [ 318],
        [ 252],
        [ 116],
        [ 297],
        [ 272],
        [  75],
        [ 166],
        [ 625],
        [ 199],
        [ 236],
        [ 972],
        [  13],
        [  17],
        [1176],
        [ 145],
        [ 698],
        [  18],
        [ 318],
        [ 591],
        [ 315],
        [ 524],
        [  67],
        [ 104],
        [1176],
        [ 585],
        [ 145],
        [ 977],
        [ 505],
        [ 145],
        [ 565],
        [ 135],
        [ 741],
        [ 615],
        [ 185],
        [ 145],
        [ 478],
        [ 112],
        [ 145],
        [ 156],
        [  76],
        [ 116],
        [ 236],
        [ 145],
        [ 478],
        [ 316],
        [ 236],
        [ 478],
        [  71],
        [ 715],
        [ 145],
        

In [ ]:
indice_maior = vetor.argmax(1)[vetor.max(1).argmax()].A[0][0]
vectorizer.get_feature_names()[indice_maior]

'defeit'

In [1]:
A = 1
B = 2


SyntaxError: ignored

In [5]:
A

1